services:
  client:
    build:
      context: ./angular-client/
    ports:
      - "4200:4200"
    command: ["ng", "serve", "--host", "0.0.0.0"]
    depends_on:
      - server
    container_name: client
    environment:
      - API_URL=http://localhost:8000
    profiles:
      - dev
    
  server:
    build:
      context: ./server/
    ports:
      - "8000:8000"
    volumes:
      - ./server/hotel_management_system:/hotel_management_system
    command: ["uvicorn", "hotel_management_system.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    depends_on:
      - db
    container_name: server

  db:
    image: postgres:17.0-alpine3.20
    env_file:
      - .env
    container_name: db


networks:
  backend:
    